# Experiment
experiment_name: sr10_w1
use_wandb: true 
wandb_project: DUMP

# Data
train_file: ./data/cosmologies_train.csv
control_file: ./data/cosmologies_control.csv
val_file: ./data/cosmologies_val.csv
test_file: ./data/cosmologies_test.csv
scalers_path: ./data/scalers.json
batch_size: 256
num_workers: 16

# Model
features_list:
  - H
  - logrhom
  - z
  - ns
lr: 0.0003
lr_factor: 0.1
lr_scheduler_patience: 300
width: 256
depth: 5

# Training
max_train_steps: 1000000
accelerator: auto
devices: 1
precision: "32"
val_check_interval: 100
val_with_desi_corner: true
patience: 5
control_sampling_rate: 10.0     # To turn off control with w0wa cosmologies, set this to 0
control_loss_weight: 1.0

# Plotting
plot_test: true
plot_kmin: 0.5
plot_kmax: 3.0