# Experiment
experiment_name: Pk lin no z no D 
use_wandb: true
wandb_project: DUMP

# Data
train_file: ./data/cosmologies_train.csv
val_file: ./data/cosmologies_val.csv
test_file: ./data/cosmologies_test.csv
scalers_path: ./data/scalers.json
batch_size: 256
num_workers: 16

# Model
features_list:
  - H
  - logrhom
  - lin_pk 
lr: 0.0003
lr_factor: 0.1
scheduler_patience: 250
width: 256
depth: 5

# Training
max_train_steps: 1_000_000
accelerator: auto
devices: 1
precision: "32"
val_check_interval: 50
val_with_desi_corner: true
patience: 10

# Plotting
plot_test: true
plot_kmin: 0.5
plot_kmax: 3.0
