# An example of a config file for neural ODE training for bacco Pk

# Experiment
experiment_name: example
use_wandb: true
wandb_project: DUMP

# Data
train_file: ./data/cosmologies_train.csv
val_file: ./data/cosmologies_val.csv
test_file: ./data/cosmologies_test.csv
scalers_path: ./data/scalers.json
batch_size: 1
num_workers: 1

# Model
features_list:
  - H
  - logrhom
  - z
  - D
  - dH_dz
  - dD_dz
  - dlogrhom_dz 
  - lin_pk
  - ns
  - sigma8
lr: 0.0003
lr_factor: 0.1
scheduler_patience: 10
width: 256
depth: 5

# Training
max_train_steps: 100
accelerator: auto
devices: 1
precision: "32"
val_check_interval: 100
val_with_desi_corner: true
patience: 5

# Plotting
plot_test: true
plot_kmin: 0.5
plot_kmax: 3.0